import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../models/achievement.dart';
import '../models/app_settings.dart';
import '../models/coping_strategy.dart';
import '../models/pss_assessment.dart';
import '../models/recommendation.dart';
import '../models/recommendation_feedback.dart';
import '../models/stressor.dart';
import '../models/user_profile.dart';
import 'firestore_service.dart';

/// Local storage service using Hive
/// Manages all offline data persistence
class StorageService {
  static const String _userBox = 'user_profile';
  static const String _assessmentsBox = 'pss_assessments';
  static const String _stressorsBox = 'stressors';
  static const String _copingBox = 'coping_strategies';
  static const String _recommendationsBox = 'recommendations';
  static const String _settingsBox = 'app_settings';
  static const String _feedbackBox = 'recommendation_feedback';
  static const String _achievementsBox = 'achievements';

  /// Initialize Hive and register adapters
  static Future<void> initialize() async {
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    Hive.registerAdapter(UserProfileAdapter());
    Hive.registerAdapter(PSSAssessmentAdapter());
    Hive.registerAdapter(StressorAdapter());
    Hive.registerAdapter(CopingStrategyAdapter());
    Hive.registerAdapter(RecommendationAdapter());
    Hive.registerAdapter(AppSettingsAdapter());
    Hive.registerAdapter(RecommendationFeedbackAdapter());
    Hive.registerAdapter(AchievementAdapter());
    Hive.registerAdapter(AchievementTypeAdapter());

    // Open boxes
    await Hive.openBox<UserProfile>(_userBox);
    await Hive.openBox<PSSAssessment>(_assessmentsBox);
    await Hive.openBox<Stressor>(_stressorsBox);
    await Hive.openBox<CopingStrategy>(_copingBox);
    await Hive.openBox<Recommendation>(_recommendationsBox);
    await Hive.openBox<AppSettings>(_settingsBox);
    await Hive.openBox<RecommendationFeedback>(_feedbackBox);
    await Hive.openBox<Achievement>(_achievementsBox);
  }

  // ============================================================================
  // USER PROFILE
  // ============================================================================

  Future<void> saveUserProfile(UserProfile profile) async {
    final box = Hive.box<UserProfile>(_userBox);
    await box.put('current_user', profile);

    // Background cloud sync (non-blocking)
    FirestoreService.syncUserProfile(profile).catchError((e) {
      debugPrint('Background profile sync failed: $e');
    });
  }

  UserProfile? getUserProfile() {
    final box = Hive.box<UserProfile>(_userBox);
    return box.get('current_user');
  }

  bool hasUserProfile() {
    return getUserProfile() != null;
  }

  Future<void> updateUserConsent() async {
    final profile = getUserProfile();
    if (profile != null) {
      profile.giveConsent();
      await saveUserProfile(profile);
    }
  }

  // ============================================================================
  // PSS ASSESSMENTS
  // ============================================================================

  Future<void> saveAssessment(PSSAssessment assessment) async {
    final box = Hive.box<PSSAssessment>(_assessmentsBox);
    await box.put(assessment.assessmentId, assessment);

    // Background cloud sync (non-blocking)
    FirestoreService.syncAssessment(assessment).catchError((e) {
      debugPrint('Background assessment sync failed: $e');
    });
  }

  List<PSSAssessment> getAllAssessments() {
    final box = Hive.box<PSSAssessment>(_assessmentsBox);
    return box.values.toList()..sort((a, b) => b.date.compareTo(a.date));
  }

  PSSAssessment? getLatestAssessment() {
    final assessments = getAllAssessments();
    return assessments.isEmpty ? null : assessments.first;
  }

  int getAssessmentCount() {
    return Hive.box<PSSAssessment>(_assessmentsBox).length;
  }

  /// Get assessments from last N days
  List<PSSAssessment> getRecentAssessments(int days) {
    final cutoffDate = DateTime.now().subtract(Duration(days: days));
    return getAllAssessments()
        .where((assessment) => assessment.date.isAfter(cutoffDate))
        .toList();
  }

  // ============================================================================
  // STRESSORS
  // ============================================================================

  Future<void> saveStressors(List<Stressor> stressors) async {
    final box = Hive.box<Stressor>(_stressorsBox);
    // Clear previous stressors for current assessment
    await box.clear();
    for (var stressor in stressors) {
      await box.add(stressor);
    }

    // Background cloud sync (non-blocking)
    // Link to latest assessment
    final latestAssessment = getLatestAssessment();
    if (latestAssessment != null && stressors.isNotEmpty) {
      FirestoreService.syncStressors(
        stressors,
        latestAssessment.assessmentId,
      ).catchError((e) {
        debugPrint('Background stressors sync failed: $e');
      });
    }
  }

  List<Stressor> getLatestStressors() {
    final box = Hive.box<Stressor>(_stressorsBox);
    return box.values.toList()
      ..sort((a, b) => b.recordedAt.compareTo(a.recordedAt));
  }

  List<Stressor> getSevereStressors() {
    return getLatestStressors().where((s) => s.isSevere).toList();
  }

  // ============================================================================
  // COPING STRATEGIES
  // ============================================================================

  Future<void> saveCopingStrategies(List<CopingStrategy> strategies) async {
    final box = Hive.box<CopingStrategy>(_copingBox);
    // Clear previous strategies for current assessment
    await box.clear();
    for (var strategy in strategies) {
      await box.add(strategy);
    }

    // Background cloud sync (non-blocking)
    // Link to latest assessment
    final latestAssessment = getLatestAssessment();
    if (latestAssessment != null && strategies.isNotEmpty) {
      FirestoreService.syncCopingStrategies(
        strategies,
        latestAssessment.assessmentId,
      ).catchError((e) {
        debugPrint('Background coping strategies sync failed: $e');
      });
    }
  }

  List<CopingStrategy> getLatestCopingStrategies() {
    final box = Hive.box<CopingStrategy>(_copingBox);
    return box.values.toList()
      ..sort((a, b) => b.recordedAt.compareTo(a.recordedAt));
  }

  List<CopingStrategy> getPassiveCopingStrategies() {
    return getLatestCopingStrategies().where((s) => s.isPassive).toList();
  }

  // ============================================================================
  // RECOMMENDATIONS
  // ============================================================================

  Future<void> saveRecommendations(List<Recommendation> recommendations) async {
    final box = Hive.box<Recommendation>(_recommendationsBox);
    for (var rec in recommendations) {
      await box.put(rec.recommendationId, rec);
    }

    // Background cloud sync (non-blocking)
    if (recommendations.isNotEmpty) {
      FirestoreService.syncRecommendations(recommendations).catchError((e) {
        debugPrint('Background recommendations sync failed: $e');
      });
    }
  }

  List<Recommendation> getAllRecommendations() {
    final box = Hive.box<Recommendation>(_recommendationsBox);
    return box.values.toList()
      ..sort((a, b) => b.generatedAt.compareTo(a.generatedAt));
  }

  List<Recommendation> getLatestRecommendations({int limit = 5}) {
    final all = getAllRecommendations();
    return all.take(limit).toList();
  }

  Recommendation? getRecommendation(String id) {
    final box = Hive.box<Recommendation>(_recommendationsBox);
    return box.get(id);
  }

  Future<void> clearOldRecommendations() async {
    final box = Hive.box<Recommendation>(_recommendationsBox);
    final cutoffDate = DateTime.now().subtract(const Duration(days: 30));

    final toDelete = box.values
        .where((rec) => rec.generatedAt.isBefore(cutoffDate))
        .map((rec) => rec.recommendationId)
        .toList();

    for (var id in toDelete) {
      await box.delete(id);
    }
  }

  Future<void> clearAllRecommendations() async {
    final box = Hive.box<Recommendation>(_recommendationsBox);
    await box.clear();
  }

  // ============================================================================
  // APP SETTINGS
  // ============================================================================

  Future<void> saveSettings(AppSettings settings) async {
    final box = Hive.box<AppSettings>(_settingsBox);
    await box.put('app_settings', settings);
  }

  AppSettings getSettings() {
    final box = Hive.box<AppSettings>(_settingsBox);
    return box.get('app_settings') ?? AppSettings();
  }

  Future<void> updateSettings(AppSettings settings) async {
    await saveSettings(settings);
  }

  // ============================================================================
  // DATA EXPORT
  // ============================================================================

  /// Get all data for export
  Map<String, dynamic> getAllDataForExport() {
    return {
      'user': getUserProfile()?.toJson() ?? {},
      'assessments':
          getAllAssessments().map((a) => _assessmentToJson(a)).toList(),
      'stressors': getLatestStressors().map((s) => _stressorToJson(s)).toList(),
      'coping_strategies':
          getLatestCopingStrategies().map((c) => _copingToJson(c)).toList(),
      'recommendations':
          getAllRecommendations().map((r) => _recommendationToJson(r)).toList(),
      'settings': _settingsToJson(getSettings()),
      'export_timestamp': DateTime.now().toIso8601String(),
    };
  }

  Map<String, dynamic> _assessmentToJson(PSSAssessment assessment) {
    return {
      'id': assessment.assessmentId,
      'date': assessment.date.toIso8601String(),
      'total_score': assessment.totalScore,
      'category': assessment.category,
      'is_crisis': assessment.isCrisis,
      'responses': assessment.responses.toString(),
    };
  }

  Map<String, dynamic> _stressorToJson(Stressor stressor) {
    return {
      'type': stressor.type,
      'severity': stressor.severity,
      'recorded_at': stressor.recordedAt.toIso8601String(),
    };
  }

  Map<String, dynamic> _copingToJson(CopingStrategy strategy) {
    return {
      'name': strategy.name,
      'frequency': strategy.frequency,
      'effectiveness': strategy.effectivenessRating,
      'recorded_at': strategy.recordedAt.toIso8601String(),
    };
  }

  Map<String, dynamic> _recommendationToJson(Recommendation rec) {
    return {
      'id': rec.recommendationId,
      'generated_at': rec.generatedAt.toIso8601String(),
      'type': rec.type,
      'priority_score': rec.priorityScore,
      'title': rec.title,
      'message': rec.message,
      'is_crisis': rec.isCrisisRecommendation,
      'is_viewed': rec.isViewed,
    };
  }

  Map<String, dynamic> _settingsToJson(AppSettings settings) {
    return {
      'total_assessments': settings.totalAssessmentsCompleted,
      'crisis_events': settings.crisisEventsLog,
      'last_assessment': settings.lastAssessmentDate?.toIso8601String(),
      'next_assessment_due': settings.nextAssessmentDue?.toIso8601String(),
    };
  }

  // ============================================================================
  // RECOMMENDATION FEEDBACK
  // ============================================================================

  Future<void> saveFeedback(RecommendationFeedback feedback) async {
    final box = Hive.box<RecommendationFeedback>(_feedbackBox);
    await box.add(feedback);
  }

  List<RecommendationFeedback> getAllFeedback() {
    final box = Hive.box<RecommendationFeedback>(_feedbackBox);
    return box.values.toList()
      ..sort((a, b) => b.viewedAt.compareTo(a.viewedAt));
  }

  RecommendationFeedback? getFeedbackForRecommendation(
      String recommendationId) {
    final box = Hive.box<RecommendationFeedback>(_feedbackBox);
    return box.values.firstWhere(
      (f) => f.recommendationId == recommendationId,
      orElse: () => box.values.first, // Return any if not found
    );
  }

  List<RecommendationFeedback> getCompletedFeedback() {
    return getAllFeedback().where((f) => f.wasCompleted).toList();
  }

  double getAverageHelpfulnessRating() {
    final feedback =
        getAllFeedback().where((f) => f.helpfulnessRating != null).toList();

    if (feedback.isEmpty) return 0.0;

    final sum = feedback.fold<int>(
      0,
      (sum, f) => sum + (f.helpfulnessRating ?? 0),
    );

    return sum / feedback.length;
  }

  // ============================================================================
  // ACHIEVEMENTS
  // ============================================================================

  Future<void> saveAchievement(Achievement achievement) async {
    final box = Hive.box<Achievement>(_achievementsBox);
    await box.put(achievement.achievementId, achievement);
  }

  Future<void> initializeAchievements() async {
    final box = Hive.box<Achievement>(_achievementsBox);

    // Only initialize if box is empty
    if (box.isEmpty) {
      final achievements = AchievementDefinitions.getAll();
      for (var achievement in achievements) {
        await box.put(achievement.achievementId, achievement);
      }
    }
  }

  List<Achievement> getAllAchievements() {
    final box = Hive.box<Achievement>(_achievementsBox);
    return box.values.toList();
  }

  List<Achievement> getUnlockedAchievements() {
    return getAllAchievements().where((a) => a.isUnlocked).toList();
  }

  List<Achievement> getLockedAchievements() {
    return getAllAchievements().where((a) => !a.isUnlocked).toList();
  }

  Achievement? getAchievement(String achievementId) {
    final box = Hive.box<Achievement>(_achievementsBox);
    return box.get(achievementId);
  }

  Future<void> updateAchievementProgress(
    String achievementId,
    int progressAmount,
  ) async {
    final achievement = getAchievement(achievementId);
    if (achievement != null) {
      achievement.incrementProgress(amount: progressAmount);
      await saveAchievement(achievement);
    }
  }

  int getAchievementCompletionPercentage() {
    final achievements = getAllAchievements();
    if (achievements.isEmpty) return 0;

    final unlocked = achievements.where((a) => a.isUnlocked).length;
    return ((unlocked / achievements.length) * 100).round();
  }

  // ============================================================================
  // CLEANUP
  // ============================================================================

  Future<void> clearAllData() async {
    await Hive.box<UserProfile>(_userBox).clear();
    await Hive.box<PSSAssessment>(_assessmentsBox).clear();
    await Hive.box<Stressor>(_stressorsBox).clear();
    await Hive.box<CopingStrategy>(_copingBox).clear();
    await Hive.box<Recommendation>(_recommendationsBox).clear();
    await Hive.box<AppSettings>(_settingsBox).clear();
    await Hive.box<RecommendationFeedback>(_feedbackBox).clear();
    await Hive.box<Achievement>(_achievementsBox).clear();
  }
}

// Extension to add toJson method to UserProfile
extension UserProfileExtension on UserProfile {
  Map<String, dynamic> toJson() {
    return {
      'user_id': userId,
      'name': name,
      'age': age,
      'gender': gender,
      'has_consented': hasConsented,
      'consent_timestamp': consentTimestamp?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
    };
  }
}
