import 'package:hive/hive.dart';

part 'recommendation.g.dart';

/// Recommendation generated by algorithm
@HiveType(typeId: 4)
class Recommendation extends HiveObject {
  @HiveField(0)
  String recommendationId;

  @HiveField(1)
  DateTime generatedAt;

  @HiveField(2)
  String type; // CRISIS_ALERT, STRESSOR_INTERVENTION, COPING_STRATEGY, etc.

  @HiveField(3)
  double priorityScore; // 0-100

  @HiveField(4)
  String title;

  @HiveField(5)
  String message;

  @HiveField(6)
  List<String> actions; // Actionable steps

  @HiveField(7)
  String evidenceBasis; // "Reduces stress by X points" etc.

  @HiveField(8)
  List<String>? resources; // Crisis hotlines, links, etc.

  @HiveField(9)
  bool isViewed;

  @HiveField(10)
  bool isCrisisRecommendation;

  Recommendation({
    required this.recommendationId,
    required this.generatedAt,
    required this.type,
    required this.priorityScore,
    required this.title,
    required this.message,
    required this.actions,
    required this.evidenceBasis,
    this.resources,
    this.isViewed = false,
    this.isCrisisRecommendation = false,
  });

  void markAsViewed() {
    isViewed = true;
    // Note: Call save through StorageService after this method
  }
}

/// Crisis hotlines for East Africa
class CrisisResources {
  static const String ugandaHotline = '0800 22 00 00';
  static const String kenyaHotline = '0800 720 990';

  static const List<Map<String, String>> hotlines = [
    {
      'name': 'Uganda Ntisa Crisis Line',
      'number': '0800 22 00 00',
      'availability': '24/7 Free',
    },
    {'name': 'Kenya Red Cross', 'number': '1199', 'availability': '24/7'},
    {
      'name': 'Befrienders Kenya',
      'number': '0722 178 177',
      'availability': 'Daily 9am-9pm',
    },
    {
      'name': 'Outside Uganda/Kenya: Find A Helpline',
      'number': 'https://findahelpline.com',
      'availability': '24/7, verified crisis lines in 130+ countries',
    },
  ];

  static String getCrisisMessage() {
    return 'Your stress level is very high. You don\'t have to face this alone. '
        'Please reach out for immediate support. If you are in immediate '
        'physical danger, contact your local emergency services right away:';
  }
}
